default:
  path: /
  controller: App\Controller\HalteplatzController::index
  methods: [GET]

halteplaetze:
  path: /api/v1/halteplaetze
  controller: App\Controller\HalteplatzController::getHalteplaetze
  methods: [GET]

users:
  path: /api/v1/users
  controller: App\Controller\HalteplatzController::getUsers
  methods: [GET]
